[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci --only=production --no-audit --no-fund"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "npm start"
